[env:nologo_esp32c3_super_mini]
platform = espressif32
board = nologo_esp32c3_super_mini
framework = arduino
monitor_speed = 115200
lib_deps =
    mikalhart/TinyGPSPlus
    bblanchon/ArduinoJson
board_build.partitions = partitions.csv
extra_scripts = pre:scripts/load_env.py